ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdev',SIZE = 75000MB)
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdev02', SIZE = 75000MB)
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdev03', SIZE = 75000MB)
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdev04', SIZE = 75000MB)
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdev05', SIZE = 75000MB)
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdev06', SIZE = 75000MB)
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdev07', SIZE = 75000MB)
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdev08', SIZE = 75000MB)
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdev09', SIZE = 75000MB)
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdev10', SIZE = 75000MB)
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdev11', SIZE = 75000MB)
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdev12', SIZE = 75000MB)
GO
