--Log on to UKDC1-PC-SQL31A
--run the following against first instance - WPGWDB02:
ALTER AVAILABILITY GROUP [WPGWAG02] MODIFY REPLICA ON N'UKDC1-PC-SQL31A\WPGWDB02' WITH 
  (SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://ukdc1-pc-sql31a.worldpay.local:50022')); -- identified the destination computer

ALTER AVAILABILITY GROUP [WPGWAG02] MODIFY REPLICA ON N'UKDC1-PC-SQL31B\WPGWDB02' WITH 
(SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://ukdc1-pc-sql31b.worldpay.local:50022'));

ALTER AVAILABILITY GROUP [WPGWAG02]  MODIFY REPLICA ON N'UKDC1-PC-SQL31A\WPGWDB02' WITH 
(PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('UKDC1-PC-SQL31B\WPGWDB02','UKDC1-PC-SQL31A\WPGWDB02')));

ALTER AVAILABILITY GROUP [WPGWAG02] MODIFY REPLICA ON N'UKDC1-PC-SQL31B\WPGWDB02' WITH 
(PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('UKDC1-PC-SQL31A\WPGWDB02','UKDC1-PC-SQL31B\WPGWDB02')));




--then run this against second instance - WPGWDB01:
ALTER AVAILABILITY GROUP [WPGWAG01] MODIFY REPLICA ON N'UKDC1-PC-SQL31A\WPGWDB01' WITH 
  (SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://ukdc1-pc-sql31a.worldpay.local:50021')); -- identified the destination computer

ALTER AVAILABILITY GROUP [WPGWAG01] MODIFY REPLICA ON N'UKDC1-PC-SQL31B\WPGWDB01' WITH 
(SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://ukdc1-pc-sql31b.worldpay.local:5022'));

ALTER AVAILABILITY GROUP [WPGWAG01]  MODIFY REPLICA ON N'UKDC1-PC-SQL31A\WPGWDB01' WITH 
(PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('UKDC1-PC-SQL31B\WPGWDB01','UKDC1-PC-SQL31A\WPGWDB01')));

ALTER AVAILABILITY GROUP [WPGWAG01] MODIFY REPLICA ON N'UKDC1-PC-SQL31B\WPGWDB01' WITH 
(PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('UKDC1-PC-SQL31A\WPGWDB01','UKDC1-PC-SQL31B\WPGWDB01')));