/**
PRE-REQ - Ensure NT AUTHORITY\SYSTEM has VIEW SERVER STATE, CONNECT SQL permissions 

**/


--1. create endpoint on all nodes
USE [master]
GO

CREATE ENDPOINT [Hadr_endpoint]
	STATE=STARTED
	AS TCP(LISTENER_PORT = 5022, LISTENER_IP=ALL)
	FOR DATA_MIRRORING(ROLE=ALL, AUTHENTICATION=WINDOWS NEGOTIATE
	,ENCRYPTION =REQUIRED ALGORITHM AES)
GO

--------------------------------
--2. create availability group
:CONNECT UKDC2-PC-PST01

USE [master]
GO
CREATE AVAILABILITY GROUP [AG01]
WITH (BASIC, AUTOMATED_BACKUP_PREFERENCE = SECONDARY,
DB_FAILOVER = OFF,
DTC_SUPPORT = NONE)
FOR 
REPLICA ON N'UKDC2-PC-PST01A' WITH (ENDPOINT_URL = N'TCP://UKDC2-PC-PST01A.worldpay.local:5022', FAILOVER_MODE = AUTOMATIC, AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, SESSION_TIMEOUT = 10, BACKUP_PRIORITY = 50, PRIMARY_ROLE(ALLOW_CONNECTIONS = ALL), SECONDARY_ROLE(ALLOW_CONNECTIONS = NO)),
	N'UKDC2-PC-PST01B' WITH (ENDPOINT_URL = N'TCP://UKDC2-PC-PST01B.worldpay.local:5022', FAILOVER_MODE = AUTOMATIC, AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, SESSION_TIMEOUT = 10, BACKUP_PRIORITY = 50, PRIMARY_ROLE(ALLOW_CONNECTIONS = ALL), SECONDARY_ROLE(ALLOW_CONNECTIONS = NO));
GO

--3. add secondary replica's to the AG 
:CONNECT UKDC2-PC-PST01B

alter availability GROUP [AG01] JOIN 
GO

